[package]
name = "todo_cli"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"]}
serde_json = "1.0.135"